name: Nightly

on:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC
  workflow_dispatch:
    inputs:
      justification:
        description: "Reason for manual run"
        required: true
      dryRun:
        description: "If true, do not upload files"
        default: true

env:
  SIMC_PROFILE: profiles/CI.simc

jobs:
  nightly-build-windows:
    name: Windows Nightly ${{ matrix.architecture }} ${{ matrix.source_branch }}
    runs-on: windows-latest
    env:
        SIMCDIR: ${{ github.workspace }}
        INSTALL: ${{ github.workspace }}\install
        uploadDir: ${{ github.workspace }}\upload
    strategy:
      matrix:
        architecture: [x86, x64]
        targetConfiguration: [Release]
        source_branch: [shadowlands, bfa-dev]
        include:
          - source_branch: shadowlands
            run_smokeTest: true
          - architecture: x86
            cl_architecture: amd64_x86
            package_suffix: win32
            qt_arch: win32_msvc2017
          - architecture: x64
            cl_architecture: x64
            package_suffix: win64
            qt_arch: win64_msvc2017_64

    steps:
      - uses: actions/checkout@v2
        with:
          repository: simulationcraft/simc
          ref: ${{ matrix.source_branch }}

      - name: Get git hash
        id: git_hash
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Add MSBuild and MS C++ Compiler to path
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.cl_architecture }}

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          modules: qtwebengine
          arch: ${{ matrix.qt_arch }}

      - name: Create Install and Upload Directory
        run: |
          mkdir ${{ env.INSTALL }}
          mkdir ${{ env.uploadDir }}

      - name: Extract Simc Version info
        id: simc_info
        env:
          configHeader: engine/config.hpp
        run: |
          $env:simc_major = Get-Content "${{ env.configHeader }}" | Select-String '#define SC_MAJOR_VERSION \"(.+)\"' | ForEach-Object {$_.Matches[0].Groups[1].Value}
          $env:simc_minor = Get-Content "${{ env.configHeader }}" | Select-String '#define SC_MINOR_VERSION \"(.+)\"' | ForEach-Object {$_.Matches[0].Groups[1].Value}
          echo "::set-output name=cli_executable::$(echo "${{ env.INSTALL }}\simc-$env:simc_major-$env:simc_minor-${{ matrix.package_suffix }}\simc.exe")"
          echo "::set-output name=simc_version::$(echo "$env:simc_major-$env:simc_minor")"
      
      - name: Build
        env:
          SC_DEFAULT_APIKEY: ${{ secrets.SC_DEFAULT_APIKEY }}
          SIMCVERSION: ${{ steps.simc_info.outputs.simc_version}}  
        run: |
          $env:QTDIR = "$env:Qt5_DIR"
          $env:SZIP = "$env:ProgramFiles\7-Zip"
          $env:GITREV = "${{ steps.git_hash.outputs.sha_short }}"
          WinReleaseScripts\build-simc.bat ${{ matrix.targetConfiguration }} ${{ matrix.architecture }}

      - name: Smoke Test
        if: ${{ matrix.run_smokeTest }}
        run: |
          & "${{ steps.simc_info.outputs.cli_executable}}" ${{ env.SIMC_PROFILE }} iterations=5 output=nul html=nul json2=nul cleanup_threads=1

      - uses: actions/upload-artifact@v2
        with:
          name: simc-nightly-${{ matrix.package_suffix }}-${{ matrix.source_branch }}
          path: ${{ env.INSTALL }}\*.7z


  nightly-upload:
    name: Nightly Upload ${{ matrix.source_branch }} ${{ matrix.package_suffix }}
    runs-on: ubuntu-latest
    needs: [nightly-build-windows]
    if: ${{ !github.event.inputs.dryRun }}
    strategy:
      matrix:
        package_suffix: [win32, win64]
        source_branch: [shadowlands, bfa-dev]

    steps:
      - name: Install sftp utils
        run: |
          sudo apt install sshpass

      - uses: actions/download-artifact@v2
        with:
          name: simc-nightly-${{ matrix.package_suffix }}-${{ matrix.source_branch }}
          path: ${{ github.workspace }}/artifacts

      # Use specific commit id here to fix known-hosts input not working.
      - name: SFTP Upload
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.UPLOAD_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          sshpass -e sftp -q ${{ secrets.UPLOAD_USER }}@${{ secrets.UPLOAD_HOST }}:${{ env.remote-dir }} <<< $'put ${{ env.local-dir }}/*.7z'

        env:
          SSHPASS: ${{ secrets.UPLOAD_PASSWORD }}
          known-hosts: ${{ secrets.UPLOAD_KNOWN_HOSTS }}
          remote-dir: /
          local-dir: ${{ github.workspace }}/artifacts
